// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: grpc/grpcProto.proto

package gRPCProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_grpc_grpcProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpcProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_grpc_grpcProto_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoReq) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRsp) Reset() {
	*x = UserInfoRsp{}
	mi := &file_grpc_grpcProto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRsp) ProtoMessage() {}

func (x *UserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpcProto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRsp.ProtoReflect.Descriptor instead.
func (*UserInfoRsp) Descriptor() ([]byte, []int) {
	return file_grpc_grpcProto_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoRsp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfoRsp) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UserInfoRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CheckLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLoginReq) Reset() {
	*x = CheckLoginReq{}
	mi := &file_grpc_grpcProto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLoginReq) ProtoMessage() {}

func (x *CheckLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpcProto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLoginReq.ProtoReflect.Descriptor instead.
func (*CheckLoginReq) Descriptor() ([]byte, []int) {
	return file_grpc_grpcProto_proto_rawDescGZIP(), []int{2}
}

func (x *CheckLoginReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CheckLoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLoginRsp) Reset() {
	*x = CheckLoginRsp{}
	mi := &file_grpc_grpcProto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLoginRsp) ProtoMessage() {}

func (x *CheckLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpcProto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLoginRsp.ProtoReflect.Descriptor instead.
func (*CheckLoginRsp) Descriptor() ([]byte, []int) {
	return file_grpc_grpcProto_proto_rawDescGZIP(), []int{3}
}

func (x *CheckLoginRsp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CheckLoginRsp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

var File_grpc_grpcProto_proto protoreflect.FileDescriptor

const file_grpc_grpcProto_proto_rawDesc = "" +
	"\n" +
	"\x14grpc/grpcProto.proto\"\x1f\n" +
	"\vUserInfoReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\"Q\n" +
	"\vUserInfoRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1c\n" +
	"\tuserEmail\x18\x02 \x01(\tR\tuserEmail\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"!\n" +
	"\rCheckLoginReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"=\n" +
	"\rCheckLoginRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName2:\n" +
	"\vUserService\x12+\n" +
	"\vGetUserInfo\x12\f.UserInfoReq\x1a\f.UserInfoRsp\"\x002C\n" +
	"\x11CheckLoginService\x12.\n" +
	"\n" +
	"checkLogin\x12\x0e.CheckLoginReq\x1a\x0e.CheckLoginRsp\"\x00B\fZ\n" +
	"/gRPCProtob\x06proto3"

var (
	file_grpc_grpcProto_proto_rawDescOnce sync.Once
	file_grpc_grpcProto_proto_rawDescData []byte
)

func file_grpc_grpcProto_proto_rawDescGZIP() []byte {
	file_grpc_grpcProto_proto_rawDescOnce.Do(func() {
		file_grpc_grpcProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_grpcProto_proto_rawDesc), len(file_grpc_grpcProto_proto_rawDesc)))
	})
	return file_grpc_grpcProto_proto_rawDescData
}

var file_grpc_grpcProto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_grpcProto_proto_goTypes = []any{
	(*UserInfoReq)(nil),   // 0: UserInfoReq
	(*UserInfoRsp)(nil),   // 1: UserInfoRsp
	(*CheckLoginReq)(nil), // 2: CheckLoginReq
	(*CheckLoginRsp)(nil), // 3: CheckLoginRsp
}
var file_grpc_grpcProto_proto_depIdxs = []int32{
	0, // 0: UserService.GetUserInfo:input_type -> UserInfoReq
	2, // 1: CheckLoginService.checkLogin:input_type -> CheckLoginReq
	1, // 2: UserService.GetUserInfo:output_type -> UserInfoRsp
	3, // 3: CheckLoginService.checkLogin:output_type -> CheckLoginRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_grpcProto_proto_init() }
func file_grpc_grpcProto_proto_init() {
	if File_grpc_grpcProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_grpcProto_proto_rawDesc), len(file_grpc_grpcProto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpc_grpcProto_proto_goTypes,
		DependencyIndexes: file_grpc_grpcProto_proto_depIdxs,
		MessageInfos:      file_grpc_grpcProto_proto_msgTypes,
	}.Build()
	File_grpc_grpcProto_proto = out.File
	file_grpc_grpcProto_proto_goTypes = nil
	file_grpc_grpcProto_proto_depIdxs = nil
}
